marks=[]
s1=int(input("enter marks of student: "))
marks.append(s1)
s2=int(input("enter marks of student: "))
marks.append(s2)
s3=int(input("enter marks of student: "))
marks.append(s3)
s4=int(input("enter marks of student: "))
marks.append(s4)
s5=int(input("enter marks of student: "))
marks.append(s5)
s6=int(input("enter marks of student: "))
marks.append(s6)
s7=int(input("enter marks of student: "))
marks.append(s7)
marks.sort()
print(marks)